nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthToken: "${NPM_TOKEN}"

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  react-native-google-signin:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN_GOOGLE_SIGN_IN}"
    npmRegistryServer: "https://npm.pkg.github.com"
